"""Compile and scan static fixture bytes; never execute fixture content."""
from __future__ import annotations
import argparse
import hashlib
import importlib.metadata
import json
from pathlib import Path
import re
import time
import zipfile

ROOT = Path(__file__).resolve().parents[1]
REQUIRED = {"author", "source", "license", "description", "category", "confidence",
            "severity", "rule_version", "created", "modified", "status", "scope",
            "limitation", "minimum_yara"}

def sha(data):
    return hashlib.sha256(data).hexdigest()

def load_library():
    files = sorted((ROOT / "rules").rglob("*.yar"))
    if not files:
        raise ValueError("No rules found")
    records, sources = {}, {}
    for file in files:
        source = file.read_text(encoding="utf-8-sig")
        sources[file.relative_to(ROOT).as_posix()] = source
        for match in re.finditer(r"\brule\s+(\w+)\s*(?::[^\{]+)?\{\s*meta:\s*(.*?)\bstrings:", source, re.S):
            name, meta_source = match.groups()
            meta = dict(re.findall(r'^\s*(\w+)\s*=\s*"([^"\n]*)"\s*$', meta_source, re.M))
            if name in records or not name.startswith("ASPL_"):
                raise ValueError(f"Duplicate or invalid rule identifier: {name}")
            missing = REQUIRED - {key for key, value in meta.items() if value.strip()}
            if missing:
                raise ValueError(f"{name}: missing metadata {sorted(missing)}")
            if meta["confidence"] not in {"low", "medium", "high"} or meta["severity"] not in {"low", "medium", "high"}:
                raise ValueError(f"{name}: invalid confidence/severity")
            if meta["license"] != "ISC" or meta["status"] != "experimental" or meta["scope"] != "static-artifact":
                raise ValueError(f"{name}: unexpected initial library policy")
            records[name] = {"file": file.relative_to(ROOT).as_posix(), "metadata": meta}
    specs = []
    for file in sorted((ROOT / "tests/specs").glob("*.json")):
        specs.extend(json.loads(file.read_text(encoding="utf-8-sig")))
    if len(specs) != len(records) or len({item["rule"] for item in specs}) != len(specs):
        raise ValueError("Exactly one test specification is required for every rule")
    for spec in specs:
        if spec["rule"] not in records or spec["file"] != records[spec["rule"]]["file"]:
            raise ValueError(f"Unknown rule/file in test spec: {spec['rule']}")
        if len(spec["negative"]) < 2 or set(spec["encoding"]) != {"utf8", "utf16le"}:
            raise ValueError(f"{spec['rule']}: need two negatives and both encodings")
    return records, sources, specs

def build(records, sources):
    (ROOT / "dist").mkdir(exist_ok=True)
    includes = '\n'.join(f'include "{file}"' for file in sources) + '\n'
    (ROOT / "main.yar").write_text('// Generated by scripts/library.py; all rules are experimental.\n' + includes, encoding="utf-8")
    bundle = '\n'.join(f'// SOURCE: {file}\n{source}' for file, source in sources.items())
    (ROOT / "dist/asphdex-yara-library.yar").write_text(bundle, encoding="utf-8", newline="\n")
    by_category = {}
    for file, source in sources.items():
        parts = Path(file).parts
        category = parts[2] if parts[1] == "behavior" else parts[1]
        by_category.setdefault(category, []).append(source)
    for category, parts in by_category.items():
        (ROOT / f"dist/{category}.yar").write_text('\n'.join(parts), encoding="utf-8", newline="\n")
    catalog = {"schemaVersion": 1, "version": "0.1.0", "status": "experimental",
               "rules": [{"id": name, **record} for name, record in sorted(records.items())]}
    (ROOT / "catalog.json").write_text(json.dumps(catalog, indent=2) + '\n', encoding="utf-8")
    manifest = {"version": "0.1.0", "files": [{"file": file.name, "sha256": sha(file.read_bytes())}
                for file in sorted((ROOT / "dist").glob("*.yar"))]}
    (ROOT / "dist/manifest.json").write_text(json.dumps(manifest, indent=2) + '\n', encoding="utf-8")
    with zipfile.ZipFile(ROOT / "dist/asphdex-yara-library-0.1.0-experimental.zip", "w", zipfile.ZIP_DEFLATED) as archive:
        for file in sorted((ROOT / "dist").glob("*.yar")):
            archive.write(file, file.name)
        archive.write(ROOT / "dist/manifest.json", "manifest.json")
        archive.write(ROOT / "LICENSE", "LICENSE")
    return bundle

def validate(records, sources, specs, bundle):
    import yara
    import yara_x
    classic = yara.compile(source=bundle)
    compiler = yara_x.Compiler()
    compiler.add_source(bundle)
    x_rules = compiler.build()
    x_scanner = yara_x.Scanner(x_rules)
    x_scanner.set_timeout(10)
    warnings = compiler.warnings()
    fixture_root = ROOT / "tests/fixtures"
    fixture_root.mkdir(parents=True, exist_ok=True)
    rows, failures = [], []
    for spec in specs:
        target = spec["rule"]
        examples = [("positive", 0, spec["positive"])]
        examples += [("negative", index, content) for index, content in enumerate(spec["negative"])]
        examples += [("documented-limitation", 0, f'Documentation quote only, never executed: {spec["positive"]}')]
        for encoding in spec["encoding"]:
            for kind, index, content in examples:
                data = ('INERT STATIC ANALYSIS FIXTURE; DO NOT EXECUTE.\n' + content).encode("utf-8" if encoding == "utf8" else "utf-16-le")
                if len(data) > 128 * 1024:
                    raise ValueError(f"Oversized fixture {target}")
                name = f"{target}-{kind}-{index}-{encoding}.txt"
                (fixture_root / name).write_bytes(data)
                started = time.perf_counter()
                a = sorted(hit.rule for hit in classic.match(data=data, timeout=10))
                b = sorted(hit.identifier for hit in x_scanner.scan(data).matching_rules)
                expected = kind != "negative"
                passed = a == b and (target in a) == expected and (kind != "negative" or not a)
                row = {"fixture": name, "target": target, "kind": kind, "sha256": sha(data),
                       "yara": a, "yara_x": b, "passed": passed,
                       "elapsedMs": round((time.perf_counter() - started) * 1000, 3)}
                rows.append(row)
                if not passed:
                    failures.append(row)
    # A shared benign corpus is scanned against the entire library, not one rule.
    for file in sorted((ROOT / "tests/benign").glob("*.txt")):
        data = file.read_bytes()
        a = sorted(hit.rule for hit in classic.match(data=data, timeout=10))
        b = sorted(hit.identifier for hit in x_scanner.scan(data).matching_rules)
        passed = not a and not b
        row = {"fixture": file.name, "target": None, "kind": "benign-corpus", "sha256": sha(data),
               "yara": a, "yara_x": b, "passed": passed}
        rows.append(row)
        if not passed:
            failures.append(row)
    # Exercise repeated anchors without a valid chain, bounded to one MiB.
    data = (b'PowerShell rundll32 mshta registry network script runtime ' * 20000)[:1024 * 1024]
    started = time.perf_counter()
    a = sorted(hit.rule for hit in classic.match(data=data, timeout=10))
    b = sorted(hit.identifier for hit in x_scanner.scan(data).matching_rules)
    row = {"fixture": "repeated-anchor-1MiB", "kind": "bounded-cost-probe", "target": None,
           "sha256": sha(data), "size": len(data), "yara": a, "yara_x": b,
           "elapsedMs": round((time.perf_counter() - started) * 1000, 3), "passed": not a and not b}
    rows.append(row)
    if not row["passed"]:
        failures.append(row)
    output = ROOT / "outputs"
    output.mkdir(exist_ok=True)
    report = {"ruleCount": len(records), "versions": {"yara-python": importlib.metadata.version("yara-python"),
              "yara-x": importlib.metadata.version("yara-x")}, "bundleSha256": sha(bundle.encode()),
              "cases": len(rows), "failed": len(failures), "warnings": warnings, "results": rows,
              "limitation": "Synthetic static artifact coverage. Documented quotations can match. Not real-world malware accuracy or production acceptance."}
    (output / "validation.json").write_text(json.dumps(report, indent=2) + '\n', encoding="utf-8")
    print(f"Rules: {len(records)}; cases: {len(rows)}; failures: {len(failures)}; compiler warnings: {len(warnings)}")
    for row in failures:
        print(json.dumps(row))
    if failures:
        raise SystemExit(1)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=["build", "test"])
    args = parser.parse_args()
    records, sources, specs = load_library()
    bundle = build(records, sources)
    if args.command == "test":
        validate(records, sources, specs, bundle)
    else:
        print(f"Built {len(records)} rules and category packages")

if __name__ == "__main__":
    main()
